#!/usr/bin/env bash

export SRC_OBJECTS="\
$SRC_OBJ_FOLDER/point.o \
$SRC_OBJ_FOLDER/salesman.o \
$SRC_OBJ_FOLDER/map.o \
$SRC_OBJ_FOLDER/selector.o \
$SRC_OBJ_FOLDER/engine.o \
$SRC_OBJ_FOLDER/basic_selectors.o"

export TEST_OBJECTS="\
$TST_OBJ_FOLDER/include/test_tools.o \
$TST_OBJ_FOLDER/PointTests.o \
$TST_OBJ_FOLDER/SalesmanTests.o \
$TST_OBJ_FOLDER/MapTests.o \
$TST_OBJ_FOLDER/EngineTests.o"
